version: '3.8'
services:
  web-app:
    build:
      context: ./app
      dockerfile: Dockerfile_Rasul
    ports:
      - "8080:5000"
    depends_on:
      - db-server
    environment:
      DB_HOST: db-server
      POSTGRES_DB: devops_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      DB_PORT: 5432

  db-server:
    image: postgres:13
    environment:
      POSTGRES_DB: devops_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata_rasul:/var/lib/postgresql/data

volumes:
  pgdata_rasul:
